name: Build, Test & Dockerize Python App

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev  # Assumes Pipfile exists

      # 4. Run tests
      - name: Run tests with pytest
        run: |
          pipenv run pytest tests/ || echo "No tests found or failed"

      # 5. Check project structure and files
      - name: Show project structure
        run: |
          echo "Files:"
          ls -la
          echo "Working directory:"
          pwd
          echo "main.py:"
          cat main.py || echo "main.py not found"
          echo "Dockerfile:"
          cat Dockerfile || echo "Dockerfile not found"
          echo "requirements.txt:"
          cat requirements.txt || echo "requirements.txt not found"

      # 6. Build Docker image
      - name: Build Docker image
        run: docker build -t my-app-image .

      # 7. (Optional) Run the Docker container to test it
      - name: Run Docker container
        run: docker run -d -p 8000:8000 my-app-image
